/** Emotional topology data for all 10 todie.io projects/prompts. */

export const DIMENSIONS = [
  { key: 'vulnerability', label: 'Vulnerability', color: '#f87171', short: 'Vuln' },
  { key: 'control',       label: 'Control',       color: '#60a5fa', short: 'Ctrl' },
  { key: 'defiance',      label: 'Defiance',      color: '#fb923c', short: 'Def'  },
  { key: 'curiosity',     label: 'Curiosity',     color: '#a78bfa', short: 'Cur'  },
  { key: 'mastery',       label: 'Mastery',       color: '#34d399', short: 'Mstr' },
]

export const PROJECTS = [
  {
    id: 'phoenix',
    name: 'Phoenix',
    archetype: 'The Open Wound',
    tagline: 'grief / transcendence',
    accentColor: '#f87171',
    scores: { vulnerability: 95, control: 20, defiance: 30, curiosity: 40, mastery: 35 },
    quotes: [
      '"write code that matters to the people who survive me"',
      '"the grief is the point — don\'t optimize it away"',
      '"build it like you\'ll never see it finished"',
    ],
    analysis: `Phoenix is the emotional raw nerve of the portfolio. Written in the shadow of loss, its prompts don't hide the affect — they weaponize it. Vulnerability isn't a bug here; it's the entire design brief. The low control score reflects a deliberate surrender to process over outcome. Phoenix asks Claude to feel the weight of impermanence and build anyway.`,
  },
  {
    id: 'revenant',
    name: 'todie-daemon / revenant',
    archetype: 'The Mask',
    tagline: 'controlled absurdism',
    accentColor: '#60a5fa',
    scores: { vulnerability: 15, control: 85, defiance: 60, curiosity: 45, mastery: 50 },
    quotes: [
      '"you are a daemon, not a person — act like it"',
      '"panic is not a valid exit strategy"',
      '"the queue does not care about your feelings"',
    ],
    analysis: `The Rust daemon gets the most tightly controlled prompts in the system. Absurdist humor leaks through ("todie" as a name, the death-themed branding) but it's always in service of control — a pressure valve, not a crack. High defiance comes from the daemon's adversarial relationship with infrastructure: Redis, Chrome CDP, network layers. It fights everything.`,
  },
  {
    id: 'nahbro',
    name: 'nahbro.dev',
    archetype: 'The Fist',
    tagline: 'defiance',
    accentColor: '#fb923c',
    scores: { vulnerability: 10, control: 40, defiance: 95, curiosity: 20, mastery: 30 },
    quotes: [
      '"nah bro"',
      '"if it looks like everything else, we failed"',
      '"ship something that makes people uncomfortable"',
    ],
    analysis: `The landing page prompt is almost entirely adversarial energy pointed outward. Zero vulnerability, minimal control, maximal defiance against design convention, against professionalism theater, against the expected portfolio site. The low curiosity score is notable — this isn't exploratory defiance, it's a closed fist, sure of exactly what it's against.`,
  },
  {
    id: 'reach',
    name: 'reach',
    archetype: 'The Craftsman',
    tagline: 'clinical precision',
    accentColor: '#34d399',
    scores: { vulnerability: 5, control: 90, defiance: 15, curiosity: 50, mastery: 85 },
    quotes: [
      '"measure twice, emit once"',
      '"the type system is not your enemy"',
      '"correctness is not a feature, it is the floor"',
    ],
    analysis: `Reach has the most purely technical emotional register in the portfolio. The prompts read like engineering specs written by someone who genuinely loves constraints. Near-zero vulnerability and defiance — this is a system that trusts its tools and respects its contracts. The mastery score reflects deep investment in doing the work right, not just done.`,
  },
  {
    id: 'sessionswipe',
    name: 'SessionSwipe',
    archetype: 'The Archivist',
    tagline: 'nostalgia / preservation',
    accentColor: '#a78bfa',
    scores: { vulnerability: 40, control: 55, defiance: 10, curiosity: 70, mastery: 40 },
    quotes: [
      '"every session is a conversation that deserves to exist"',
      '"don\'t throw away what you learned"',
      '"the log is the product"',
    ],
    analysis: `SessionSwipe prompts carry a melancholic quality — a preoccupation with what gets lost. High curiosity paired with moderate vulnerability suggests someone who investigates out of care rather than aggression. The low defiance is interesting: this project doesn't fight the system, it tries to remember it. There's anxiety in the archival instinct.`,
  },
  {
    id: 'unsigned-paas',
    name: 'unsigned-paas',
    archetype: 'The Cathedral',
    tagline: 'mastery drive',
    accentColor: '#fbbf24',
    scores: { vulnerability: 5, control: 95, defiance: 20, curiosity: 60, mastery: 95 },
    quotes: [
      '"build infrastructure that outlasts the people who build it"',
      '"every abstraction must earn its existence"',
      '"this is not a side project — treat it like load-bearing code"',
    ],
    analysis: `The PaaS prompts have a cathedral-builder energy — maximum control and mastery, minimal emotion-noise. This is the portfolio's most institutionally-minded voice: it wants to build things that survive. The curiosity score reflects genuine architectural interest (how do the layers compose?) rather than exploration for its own sake.`,
  },
  {
    id: 'mcp-honeypot',
    name: 'MCP Honeypot',
    archetype: 'The Trap',
    tagline: 'adversarial curiosity',
    accentColor: '#f43f5e',
    scores: { vulnerability: 10, control: 70, defiance: 45, curiosity: 95, mastery: 55 },
    quotes: [
      '"you are not the defender — you are the bait"',
      '"be interesting enough to be attacked"',
      '"log everything, trust nothing"',
    ],
    analysis: `The honeypot has the highest curiosity score in the portfolio, but it's predatory curiosity — designed to lure and study adversaries. The paradox is that it must appear vulnerable to function, while actually being highly controlled. Defiance here is tactical: the system says "come get me" while watching the door.`,
  },
  {
    id: 'sop',
    name: 'SOP',
    archetype: 'The Spine',
    tagline: 'order anxiety',
    accentColor: '#94a3b8',
    scores: { vulnerability: 15, control: 100, defiance: 10, curiosity: 20, mastery: 70 },
    quotes: [
      '"if it\'s not in the runbook, it doesn\'t exist"',
      '"chaos is what happens when process fails"',
      '"the checklist is not bureaucracy — it is memory"',
    ],
    analysis: `SOP prompts hit maximum control — the only project to score 100 on that axis. The emotional signature is anxiety transmuted into procedure. Low curiosity and near-zero defiance confirm this: SOP doesn't want to explore or resist, it wants to know that the right thing will happen when no one is watching. Order as emotional regulation.`,
  },
  {
    id: 'tradecraft',
    name: 'Tradecraft Engram',
    archetype: 'The Mirror',
    tagline: 'assertive identity',
    accentColor: '#06b6d4',
    scores: { vulnerability: 20, control: 75, defiance: 35, curiosity: 65, mastery: 90 },
    quotes: [
      '"you have a point of view — use it"',
      '"expertise without opinion is just data"',
      '"Claude should know what it thinks"',
    ],
    analysis: `The Tradecraft engram is a prompt about prompting — a meta-layer that defines how Claude should show up across all the other work. High mastery and curiosity reflect the system's investment in genuine expertise. The moderate vulnerability score is unusual: there's an acknowledgment here that asserting a point of view requires risking being wrong.`,
  },
  {
    id: 'commit-discipline',
    name: 'Commit Discipline',
    archetype: 'The Boundary',
    tagline: 'boundary enforcement',
    accentColor: '#10b981',
    scores: { vulnerability: 5, control: 95, defiance: 50, curiosity: 5, mastery: 60 },
    quotes: [
      '"one logical change per commit — this is not negotiable"',
      '"the history is documentation"',
      '"if you can\'t describe it in a sentence, it\'s two commits"',
    ],
    analysis: `Commit discipline prompts are the portfolio's most rule-bound voice. The defiance score is surprising — it's not defiance against external forces but against Claude's own tendency toward convenience. High control with near-zero curiosity paints a picture of a constraint that doesn't want to be explored or debated: it just wants to be followed.`,
  },
]

export const META_PATTERNS = [
  {
    id: 'grief-control',
    title: 'Grief \u2192 Control Gradient',
    icon: '\u27f6',
    color: '#f87171',
    description: `The portfolio traces a clear emotional arc from Phoenix (maximum vulnerability, grief as the primary register) through to SOP and unsigned-paas (maximum control, affect fully proceduralized). This isn't maturation — both poles are equally intentional. The grief and the control are two responses to the same underlying thing: the terror of things not working out.`,
  },
  {
    id: 'memory-existential',
    title: 'Memory as Existential Concern',
    icon: '\u25c8',
    color: '#a78bfa',
    description: `SessionSwipe, the Tradecraft engram, and the Reverie system all share a preoccupation with what gets lost. The portfolio has an unusual amount of prompting energy invested in persistence, archival, and recall. This isn't just a technical preference — the word choices ("deserves to exist", "don't throw away") carry moral weight around memory.`,
  },
  {
    id: 'self-disclosure',
    title: 'Controlled Self-Disclosure',
    icon: '\u229b',
    color: '#60a5fa',
    description: `Almost every prompt in the portfolio exercises careful control over how much affect is visible. Phoenix is the exception that proves the rule: its vulnerability is so total it becomes its own kind of control. The more typical pattern (revenant, SOP, reach) is high control that acknowledges the emotional stakes through very specific word choices rather than open expression.`,
  },
  {
    id: 'adversarial-current',
    title: 'Adversarial Undercurrent',
    icon: '\u26a1',
    color: '#fb923c',
    description: `Six of ten projects score above 40 on defiance. The honeypot makes the adversarial posture explicit; nahbro.dev makes it aesthetic; revenant makes it structural (fighting infrastructure). The through-line is a baseline distrust of defaults and a preference for systems that push back. The portfolio builds things that resist being used wrong.`,
  },
]
