/** Registry of all explainers — add new ones here. */
export const EXPLAINERS = [
  {
    id: 'memory-model',
    title: 'Memory Model',
    short: 'How Claude Code remembers',
    icon: '🧠',
    path: '/memory-model',
    tags: ['engram', 'context', 'memory', 'retrieval', 'injection', 'claude'],
  },
  {
    id: 'gestalt',
    title: 'Gestalt Thinking',
    short: 'Seeing wholes, not parts',
    icon: '👁\uFE0F',
    path: '/gestalt',
    tags: ['gestalt', 'perception', 'thinking', 'cognition', 'patterns', 'holistic'],
  },
  {
    id: 'prompt-cache',
    title: 'Caching Prompt Proxies',
    short: '90% cheaper API calls',
    icon: '🔄',
    path: '/prompt-cache',
    tags: ['cache', 'proxy', 'tokens', 'api', 'cost', 'anthropic', 'prefix'],
  },
  {
    id: 'lsp',
    title: 'Language Server Protocol',
    short: 'How code intelligence works',
    icon: '🔌',
    path: '/lsp',
    tags: ['lsp', 'language', 'server', 'protocol', 'ide', 'completion', 'diagnostics'],
  },
  {
    id: 'token-optimization',
    title: 'Token Optimization',
    short: 'Every technique to spend less',
    icon: '💰',
    path: '/token-optimization',
    tags: ['tokens', 'optimization', 'cost', 'efficiency', 'compression', 'rtk', 'caching'],
  },
  {
    id: 'reverie',
    title: 'Reverie',
    short: 'Neuroscience-grounded memory consolidation',
    icon: '💤',
    path: '/reverie',
    tags: ['reverie', 'memory', 'neuroscience', 'consolidation', 'sleep', 'engram', 'locomo', 'daemon', 'hierarchy'],
  },
  {
    id: 'emotional-topology',
    title: 'Emotional Topology',
    short: 'The affect inside the prompts',
    icon: '🧬',
    path: '/emotional-topology',
    tags: ['emotion', 'prompts', 'affect', 'vulnerability', 'control', 'defiance', 'curiosity', 'mastery', 'todie'],
  },
  {
    id: 'pidgin-tokens',
    title: 'Pidgin Tokens',
    short: 'Pirate vs caveman vs eight pidgins',
    icon: '🏴‍☠️',
    path: '/pidgin-tokens',
    tags: ['tokens', 'tokenizer', 'bpe', 'pidgin', 'creole', 'naija', 'singlish', 'krio', 'pirate', 'caveman', 'cost', 'optimization'],
  },
  {
    id: 'embodied-mind',
    title: 'The Body Is Not A Vessel',
    short: 'Mind/body dualism is empirically dead',
    icon: '🫀',
    path: '/embodied-mind',
    tags: ['embodied', 'cognition', 'mind', 'body', 'dualism', 'descartes', 'interoception', 'vagus', 'gut-brain', 'damasio', 'neuroscience', 'phenomenology', 'embodiment'],
  },
  {
    id: 'harness',
    title: 'The Harness: Beyond Vibes',
    short: 'Running Claude Code like infrastructure',
    icon: '⚙\uFE0F',
    path: '/harness',
    tags: ['harness', 'claude-code', 'hooks', 'rtk', 'engram', 'reverie', 'memory', 'specification', 'agentic', 'manifesto', 'tooling', 'infrastructure', 'consolidation'],
  },
]
